version: "3"
services:
  travel-plan-mongo:
    image: mongo:4.0
    container_name: mongo
    command: --smallfiles
    ports:
      - 27017:27017
    volumes:
      - /opt/mongodb:/data/db

  travel-plan-redis:
    image: redis:5.0.5
    container_name: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/logs:/logs
