version: "3"
services:
  travel-plan-mongo:
    image: mongo:4.0
    container_name: mongo
    command: --smallfiles
    ports:
      - 27017:27017
    volumes:
      - /opt/mongodb:/data/db

  travel-plan-redis:
    image: redis:5.0.5
    container_name: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/logs:/logs

  travel-plan-eureka:
    build: ./microservicecloud/microservicecloud-eureka-7001
    ports:
      - "7001:7001"

  travel-plan-api:
    build: ./microservicecloud/microservicecloud-provider-dept-hystrix-8001
    ports:
      - "8001:8001"
    extra_hosts:
      - "eureka7001.com:192.168.62.113"
    links:
     - travel-plan-eureka:eureka7001
