server:
  port: 80
  
spring: 
  application:
    name: microservicecloud-dept-consumer
 
feign: 
  hystrix: 
    enabled: true

eureka:
  client:
    register-with-eureka: true
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ 
  instance:
    instance-id: microservicecloud-feign  #custom the name related to feign consumer
    prefer-ip-address: true     #display IP address
      
      
       