pipeline{
    environment{
        registry = "gofnusiss/travel-plan"
        registryCredential = "dockerhub_id"
        build_version = ''
    }
    agent any

    stages{

		stage('Clean Docker Containers'){
		    steps {
		        script{
		            try{
		                sh (script: 'sudo docker kill $(sudo docker ps -q)')
		                sh (script: 'sudo docker rm $(sudo docker ps -a -q)')
		            } catch (err){
		                echo err.getMessage()
		            }
		        }
		    }
		}

        stage('Maven API builds and Publish'){
            steps {
                sh (script: 'mvn -f microservicecloud/pom.xml clean install')
            }
        }

        stage('Run API Automated Test'){
            steps {
                sh 'mkdir -p qa'
                dir("qa"){
                    git 'https://akashdktyagi:f7898852fec02d26702c629e4283ef0a329892ec@github.com/GoF-NUS-ISS/travel-plan-qa.git'
                    sh('ls')
                    sh (script: 'mvn clean test')
                }
            }
        }
        
        /*
		stage('Clean Docker Container'){
		    steps {
		        script{
		            try{
		                sh (script: 'sudo docker kill $(sudo docker ps -q)')
		                sh (script: 'sudo docker rm $(sudo docker ps -a -q)')
		            } catch (err){
		                echo err.getMessage()
		            }
		        }
		    }
		}
        */
		/*
        stage('Trivy Security Scan travel-plan-api'){
            steps {
                sh(script: 'trivy image gofnusiss/travel-plan-api')
            }
        }

        stage('Trivy Security Scan travel-plan-eureka-api'){
            steps {
                sh(script: 'trivy image gofnusiss/travel-plan-eureka-api')
            }
        }

        stage('Trivy Security Scan travel-plan-zuul-api'){
            steps {
                sh(script: 'trivy image gofnusiss/travel-plan-zuul-api')
            }
        }
		*/
       /*
        stage('Run API Automated Test'){
            steps {
                git 'https://github.com/GoF-NUS-ISS/travel-plan-qa.git' .....
                sh (script: 'mvn -f travel-plan-qa/pom.xml clean test')
            }
        }
        */
		
    }
}
