pipeline{
    environment{
        registry = "https://index.docker.io/v1/"
        registryCredential = "dockerhub_id"
    }
    agent any

    stages{

		stage('Clean Docker Containers'){
		    steps {
		        script{
		            try{
		                sh (script: 'sudo docker kill $(sudo docker ps -q)')
		                sh (script: 'sudo docker rm $(sudo docker ps -a -q)')
		            } catch (err){
		                echo err.getMessage()
		            }
		        }
		    }
		}

        //This step will create the docker image and push to the registry
        //However, as of now no integration tests are executed.
        //Planning to add Unit test which will be executed at maven test phase
        stage('Maven API builds and Publish'){
            steps {
                sh (script: 'mvn -f microservicecloud/pom.xml clean install -P staging')
            }
        }

        //Bringing the Docker containers up
        //Passing tag before docker-compose is triggered
        //This tag will then be passes inside docker-compose yml file
        stage('Run API Docker Compose'){
            steps {
                sh ('''
                PROPERTY_FILE=microservicecloud/microservicecloud-provider-dept-hystrix-8001/target/version.txt
                tag=`cat $PROPERTY_FILE`
                sudo api_tag=$tag docker-compose -f microservicecloud/docker-compose.yml up --build -d

                ''')
            }
        }

        //This will trigger API centeric integration test
        stage('Run API Automated Test'){
            steps {
                sh 'mkdir -p qa'
                dir("qa"){
                    git 'https://akashdktyagi:f7898852fec02d26702c629e4283ef0a329892ec@github.com/GoF-NUS-ISS/travel-plan-qa.git'
                    sh('ls')
                    sh (script: 'mvn clean test -Prun-api')
                }
            }
        }

        /*
            Security Vulnerabilty check for Docker containers
        Need to figure out a way to pass tag from above to this step
        stage('Trivy Security Scan travel-plan-api'){
            steps {
                sh(script: 'trivy image gofnusiss/travel-plan-api')
            }
        }

        stage('Trivy Security Scan travel-plan-eureka-api'){
            steps {
                sh(script: 'trivy image gofnusiss/travel-plan-eureka-api')
            }
        }

        stage('Trivy Security Scan travel-plan-zuul-api'){
            steps {
                sh(script: 'trivy image gofnusiss/travel-plan-zuul-api')
            }
        }
    */
        stage('Clean Docker Container'){
            steps {
                script{
                    try{
                        sh (script: 'sudo docker kill $(sudo docker ps -q)')
                        sh (script: 'sudo docker rm $(sudo docker ps -a -q)')
                    } catch (err){
                        echo err.getMessage()
                    }
                }
            }
        }
    }
}
/*
                sh ('''
                PROPERTY_FILE=microservicecloud/microservicecloud-provider-dept-hystrix-8001/git.properties
                PROP_KEY_1=git.commit.time
                PROP_KEY_2=git.commit.id.abbrev
                PROP_VALUE_1=`cat $PROPERTY_FILE | grep "$PROP_KEY_1" | cut -d'=' -f2`
                PROP_VALUE_2=`cat $PROPERTY_FILE | grep "$PROP_KEY_2" | cut -d'=' -f2`
                build_version=$PROP_VALUE_1.$PROP_VALUE_2
                echo $build_version
                export api-tag=$build_version
                sudo docker-compose up -d
                ''')
                */
