server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.gof.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  file:
    name: ./log/travel-plan-api.log
spring:
   application:
    name: microservicecloud-travel-plan
   data: 
    mongodb: 
      uri: mongodb://mongo:27017
      database: travelplan
   redis:
      database: 0
      host: redis
      port: 6379
      password: 
      timeout: 10000
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/cloudDB01
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
   elasticsearch: 
    rest: 
      uris: elasticsearch:9200
      
eureka:
  client: #client register into eureka
    service-url: 
      defaultZone: http://eureka1:7001/eureka/
  instance:
    instance-id: microservicecloud-travel-plan8001-hystrix
    prefer-ip-address: true
      
info:
  app.name: gof-microservicecloud
  company.name: www.gof.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
