server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.gof.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  file:
    name: ./log/travel-plan-api.log

spring:
   application:
    name: microservicecloud-travel-plan
   data:
     mongodb:
       uri: mongodb://localhost:27017/
       database: travelplan
      
eureka:
  client: #client register into eureka
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001-hystrix
    prefer-ip-address: true
      
info:
  app.name: gof-microservicecloud
  company.name: www.gof.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
      
      
      
 

