# This workflow will build a Java project with Maven 8f6a2be1-837a-4a61-9678-36c934eef090
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# variable in maven command: $DOCKER_HUB_REPO_SECRET_KEY, value to this is defined in github secrets for the org gof-nus-iss-->settings-->secrets
# This is a CI Pipeline. Will be triggered on staging branch.
# This includes unit tests and docker build step as well as spinning the containers.
name: Java CI with Maven

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    #- name: Set up JDK 1.8
    #  uses: actions/setup-java@v1
    #  with:
    #    java-version: 1.8
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven for PR
      if: ${{ github.event_name == 'pull_request' }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -f microservicecloud/pom.xml clean install -Psonar org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      
    - name: Build with Maven for PUSH
      if: ${{ github.event_name == 'push' }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        docker_hub_user_name: ${{ secrets.DOCKER_HUB_USER_NAME }}
        docker_hub_password: ${{ secrets.DOCKER_HUB_REPO_SECRET_KEY }}
      run: mvn -f microservicecloud/pom.xml clean install -Psonar org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Pstaging -Djib.to.auth.username=333743 -Djib.to.auth.password=$docker_hub_password
