# This workflow will build a Java project with Maven 8f6a2be1-837a-4a61-9678-36c934eef090
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#run: mvn -B package --file pom.xml
# run: mvn -f microservicecloud/pom.xml clean install -P staging jib:build -Djib.to.auth.username=333743 -Djib.to.auth.password=Clockwise@86 -X
name: Java CI with Maven

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
       run: mvn -f microservicecloud/pom.xml clean install -P staging
