# This workflow will build a Java project with Maven 8f6a2be1-837a-4a61-9678-36c934eef090
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# variable in maven command: $DOCKER_HUB_REPO_SECRET_KEY, value to this is defined in github secrets for the org gof-nus-iss-->settings-->secrets
name: Java CI with Maven

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven for PR
      if: ${{ github.event_name == 'pull_request' }}
      env:
        docker_hub_password: ${{ secrets.DOCKER_HUB_REPO_SECRET_KEY }}
      run: mvn -f microservicecloud/pom.xml clean install -Djib.to.auth.username=333743 -Djib.to.auth.password=$docker_hub_password
      
    - name: Build with Maven for PUSH
      if: ${{ github.event_name == 'push' }}
      env:
        docker_hub_password: ${{ secrets.DOCKER_HUB_REPO_SECRET_KEY }}
      run: mvn -f microservicecloud/pom.xml clean install -Pstaging -Djib.to.auth.username=333743 -Djib.to.auth.password=$docker_hub_password
